export default teamData = {
  players: [
    {
      id: '1',
      name: 'Tamim Iqbal',
      role: 'batsman',
      credit: 10,
      team: 'a',
    },
    {
      id: '2',
      name: 'Mashrafee Murtoza',
      role: 'bowler',
      credit: 9,
      team: 'b',
    },
    {
      id: '3',
      name: 'Mushfique',
      role: 'batsman',
      credit: 9,
      team: 'a',
    },
    {
      id: '4',
      name: 'Alamin Hossain',
      role: 'bowler',
      credit: 11,
      team: 'a',
    },
    {
      id: '5',
      name: 'A',
      role: 'bowler',
      credit: 8,
      team: 'a',
    },
    {
      id: '6',
      name: 'B',
      role: 'batsman',
      credit: 15,
      team: 'a',
    },
    {
      id: '7',
      name: 'C',
      role: 'bowler',
      credit: 17,
      team: 'a',
    },
    {
      id: '8',
      name: 'D',
      role: 'batsman',
      credit: 2,
      team: 'a',
    },
    {
      id: '9',
      name: 'E',
      role: 'bowler',
      credit: 5,
      team: 'a',
    },
    {
      id: '10',
      name: 'F',
      role: 'batsman',
      credit: 11,
      team: 'a',
    },
    {
      id: '11',
      name: 'G',
      role: 'bowler',
      credit: 15,
      team: 'a',
    },
    {
      id: '12',
      name: 'H',
      role: 'batsman',
      credit: 20,
      team: 'a',
    },
    {
      id: '13',
      name: 'I',
      role: 'bowler',
      credit: 14,
      team: 'a',
    },
    {
      id: '14',
      name: 'J',
      role: 'batsman',
      credit: 9,
      team: 'a',
    },

    {
      id: '15',
      name: 'K',
      role: 'bowler',
      credit: 8,
      team: 'a',
    },
  ],
};
